rauc/rauc-hawkbit-updater

src/hawkbit-client.c

Problem is that the g_message call at hawkbit-client.c:618
is passing the file size as %ld in format. Must be %lld due
to the data type holding the file size. If this is not changed
the application will segfault in a strlen call in extension of
the g-message call.
Also the g_strdup_printf call at hawkbit-client.c:624 should
have the %ld changed to %lld.
Keeping the %ld entries also produces compiler warnings in GCC 8.2.0
Signed-off-by: Niklas Johansson <niklas.johansson@prevas.dk>

corrects formating to g_message of file size

---

.travis.yml
include/hawkbit-client.h
src/hawkbit-client.c
src/rauc-hawkbit-updater.c
test/create_test_target
test/lib-sharness/functions.sh
test/rauc-hawkbit-updater.t
test/sharness.sh
test/test-config.conf
test/wait-for-hawkbit-online

This series consists of mutliple pre-work and adaptions required for running a minimum set of runtime tests for rauc-hawkbit-updater.
* Add sharness shell test suite
* Prepare code for returning error codes in ase of failures
* spawn hawkbit using docker from travis test
* simple tests for token-based authentification with hawkbit

Add minimal shell test suite and allow testing against docker hawkbit instance

---

src/config-file.c

This fixes the handling of GError's in config-file.c in many different ways.
As a result of this, no segmentation faults caused by unset errors should be triggered anymore and parsing of broken configuration should return valid error messages.
Fixes #23
Replaces #24

Fix Error Handling in config-file.c

---

.uncrustify.cfg

Per uncrustify's documentation:
```
'switch',
sp_before_sparen                = add      # ignore/add/remove/force
```

uncrustify: set sp_before_sparen to correct "add" value

---

src/hawkbit-client.c

This reworks GError handling for `get_binary()` to make it compatible with GError handling guidelines and finally allow to safely use the returned value to report errors causes to the user.

src/hawkbit-client: Rework GError handling of get_binary()

---

README.md
config.conf.example

Rearranged the comments in the config.conf.example to avoid a
segmentation fault when parsing the configuration file.

Rearranged comments in config.conf.example

---

src/hawkbit-client.c

I missed the const, when I reviewed PR #32.
This should remove the compiler warning in newer gcc.

Fix compiler warning in newer gcc

---

src/config-file.c

GKeyFile is declared with g_autofree which is wrong. This fix use
g_autoptr with auto cleanup function registered for GKeyFile.
How it is related to segfault in #21, I'm not sure.
Fixes #21
Signed-off-by: Lasse K. Mikkelsen <lasse.klok@prevas.dk>

Fix autofree of GKeyFile in config-file.c

---

.travis.yml
CMakeLists.txt
src/hawkbit-client.c
src/sd-helper.c

This was introduced and overseen in #47.
However, this clearly triggered a compiler warning but that was not discovered. For that reason, this PR also includes building the code with `-Werror` in Travis so that all compiler warnings a treated as errors and will let the build fail visibly.

Fix wrong assignment of char* to char

---

src/hawkbit-client.c

Prevent dereferencing of NULL objects returned by rest requests by simply returning false immediately rather than processing the error any further.
This fixes issue #43.

src/hawkbit-client: Prevent unref of NULL object for rest request

---

src/hawkbit-client.c

In case `regex_groups()` call fails, `deployment` will not be freed.
Simply use autopointer here to fix this.

src/hawkbit-client: fix potential gchar leakage in process_deployment()

---

src/hawkbit-client.c

There is no special reason for not doing this and most tools using curl
have this enabled (including rauc) thus we allow redirects here too,
but with a limit of 5 redirects which seems to be a common default.
Fixes #40

src/hawkbit-client: allow following HTTP redirects

---

include/config-file.h
include/hawkbit-client.h
include/json-helper.h
include/log.h
include/rauc-installer.h
include/sd-helper.h
src/config-file.c
src/hawkbit-client.c
src/json-helper.c
src/log.c
src/rauc-hawkbit-updater.c
src/rauc-installer.c

This is a manual cleanup of includes supported by the clang tool 'include-what-you-use'.
This also fixes #41 now.
The reports were generated with
``` sh
mdkir build
cd build/
cmake -DCMAKE_C_INCLUDE_WHAT_YOU_USE="iwyu" ..
make
```

Clean up includes

---

src/hawkbit-client.c

libcurl documentation for `CURLINFO_RESPONSE_CODE` notes:
> Pass a pointer to a long to receive the last received HTTP, FTP or
> SMTP response code.
Passing only an integer instead can lead to a segfault as unrelated
memory is overridden.

src/hawkbit-client: use long for CURLINFO_RESPONSE_CODE

---

src/hawkbit-client.c

The number of available bytes of storage calculated can overflow when there is too much free space.
On a machine where long is only 32 bits in size the overflow occurs with more than about 2 GB available.
The `get_available_space()` function then reports a negative value and the rollout fails with "Not enough free space" e.g..
`Error: Not enough free space. File size: 71264324. Free space: -94932992`

Fix free storage space calculation overflowing

---

.gitignore

uncrustify leftovers are not ignored. This commit update  .gitignore to discard such files from being staged by mistake. 
This PR closes #57

.gitignore: Ignore Add uncrustify temporary files

---

include/json-helper.h
src/hawkbit-client.c
src/json-helper.c

This is the first of a series of PRs to refactor and clean up the code base, get rid of bugs (memory leaks, use-after-frees, race conditions), simplify functions and document them.
In this iteration I focused on the `json-helper` module (which required some minor changes in `hawkbit-client`).

json-helper: documentation, refactoring and bug fixes

---

include/sd-helper.h
src/sd-helper.c

This is the second of a series of PRs to refactor and clean up the code base, get rid of bugs (memory leaks, use-after-frees, race conditions), simplify functions and document them.
Clean and improve functions:
- update documentation
- separate variable declaration and code
- sanity check input arguments
- wrap long lines

sd-helper: minor refactoring

---

include/config-file.h
include/hawkbit-client.h
src/config-file.c
src/hawkbit-client.c
src/rauc-hawkbit-updater.c
test/rauc-hawkbit-updater.t

This is the third of a series of PRs to refactor and clean up the code base, get rid of bugs (memory leaks, use-after-frees, race conditions), simplify functions and document them.
In this iteration I focused on the `config-file` module (which required some minor changes in `hawkbit-client`).

config-file: documentation, refactoring and bug fixes

---

include/rauc-installer.h
src/rauc-installer.c

This is the fourth of a series of PRs to refactor and clean up the code base, get rid of bugs (memory leaks, use-after-frees, race conditions), simplify functions and document them.
In this iteration I focused on the `rauc-installer` module.

rauc-installer: refactoring and bug fixes

---

include/log.h
src/log.c

- add a missing return in log_level_to_string()'s doc string
- move non-static setup_logging()'s doc string to header file

log: update/move doc strings

---

.github/workflows/tests.yml

Since PR builds from forks do not have access to the GitHub repositories
secrets, a PR will fail logging in to docker:
```
Run docker/login-action@v1
with:
logout: true
Error: Username and password required
```
Fix this by limiting the use of login-action@v1 to master branch.

.github: tests: use secrets for docker login only for master builds

---

README.md

Since 5f366cf5 (".travis.yml: drop, in favor of GitHub actions"), PR #69, GitHub Actions is used instead of TravisCI.

README: use GitHub Actions badge instead of TravisCI

---

.github/workflows/tests.yml

Otherwise, we could end up with a deprecated package cache and fail to install packages not downloadable anymore.

.github: tests: run apt-get update before install

---

include/hawkbit-client.h
src/hawkbit-client.c

This is a collection of simplifications in the `hawkbit-client` module. Conflicts with the already open PRs should be minimal.
Note that this PR blocks the (to be created) `hawkbit-client` refactoring PR.

hawkbit-client: various simplifications

---

test/create_test_target

hawkBit's default of "authentication.targettoken.enabled" changed from true to false:
https://github.com/eclipse/hawkbit/pull/1074
Enable the config option explicitly to make our tests work again.

test: create_test_target: enable target security token authentication via MGMT API

---

CMakeLists.txt
src/rauc-hawkbit-updater.c

This is the final PR of a series of refactoring PRs (#63, #64, #65, #66, #68, #71, #77). This makes sure we keep up the newly gained code quality via critical messages being turned fatal and a set of compiler warnings.

Make critical messages fatal, add useful compiler warnings

---

include/hawkbit-client.h
include/rauc-installer.h
src/hawkbit-client.c
src/rauc-hawkbit-updater.c
src/rauc-installer.c

We have a main loop, which starts the download thread if an update is available for the target. The download thread starts the install thread once the download succeeded. Currently the threads do not wait for each other to finish on `-r, --run-once`, but terminate early.
In order to test download and installation cases with `-r, --run-once` and allow use cases such as #73, the threads need to wait for each other to finish. It is also required to emit an appropriate exit code for download and installation errors.
This PR allows the threads to wait for each other to finish on `-r, --run-once` and implements status propagation.

test preparations: make threads wait for each other on --run-once, propagate results

---

script/rauc-hawkbit-updater.service

Start the systemd service only after the network is up. If the rauc-hawkbit-updater starts too early without reaching its configured
hawkBit server, network errors occur. Choosing the network-online.target instead of the network.target prevents this.
See also https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/.
In my particular case, I got the following error messages (with debugging options enabled) without this fix:
```
root@hostname:~# journalctl --no-pager -fu rauc-hawkbit-updater
-- Logs begin at Tue 2021-04-27 09:37:12 UTC. --
Apr 27 09:37:14 hostname systemd[1]: Started HawkBit client for Rauc.
Apr 27 09:37:15 hostname rauc-hawkbit-updater[378]: Checking for new software...
Apr 27 09:37:15 hostname rauc-hawkbit-updater[378]: Scheduled check for new software failed …
```

Start systemd service after network-online.target

---

include/config-file.h
include/hawkbit-client.h
include/json-helper.h
include/log.h
include/rauc-installer.h
include/sd-helper.h
src/config-file.c
src/hawkbit-client.c
src/json-helper.c
src/log.c
src/rauc-hawkbit-updater.c
src/rauc-installer.c
src/sd-helper.c

- add `SPDX-FileCopyrightText` to file headers
- drop redundant license headers
- clean up and drop redundant metadata from file headers

Clean up source file headers

---

docs/reference.rst

- mention (non-obvious) mandatory [device] section with at least one key-value pair
- use `option=<type>` syntax consistently

docs: reference: document mandatory [device] section, keep syntax consistent

---

include/rauc-installer.h
src/rauc-installer.c

In "run_once" operation mode, the download thread waits for the install thread to finish. In this case the download thread reads the installation's status result from the install_context struct.
The installation thread frees the install_context before the installation thread reads the status result. Fix that by letting the
installation thread know when to leave the freeing of the install_context struct to the download thread.
Found with address sanitizer (`-fsanitize=address`).
Fixes: 90fcb8db ("rauc-installer: let rauc_install() return result to allow install->download thread propagation")
Fixes #80

rauc-installer: fix install_context use-after-free on wait

---

src/rauc-installer.c

This fixes memory leaks for these test cases:
- test_install_bundle_no_dbus_iface
- test_install_success (happens sometimes)
- test_install_failure (happens sometimes)
```
Direct leak of 8 byte(s) in 1 object(s) allocated from:
#0 0x7f5eac3a5037 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
#1 0x7f5eabfebda0 in g_malloc0 (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x57da0)
#2 0x7f5eac2353e9  (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0+0x1183e9)
#3 0x7f5eac2361bb  (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0+0x1191bb)
#4 0x7f5eac1978e1 in g_initable_new_valist (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0+0x7a8e1)
#5 0x7f5eac197998 in g_initable_new (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0+0x7a998)
#6 0x55ba3477d697 in r_installer_proxy_new_for_bus_sync …
```

rauc-installer: process pending events before unreffing loop context

---

.github/workflows/tests.yml

Using `-fsanitize=address  -fsanitize=leak -g` can reveal critical issues, so add that to the GitHub Actions run.
`ASAN_OPTIONS=fast_unwind_on_malloc=0` makes sure the stack traces are complete.

github: use address/leak sanitizer

---

src/config-file.c
test/conftest.py
test/test_basics.py

It is not expected that trailing spaces from a config option are used, so strip them. This avoids situations where a trailing space in target_name breaks URLs and more.
Note that trailing spaces in integer option values are already ignored since GLib 2.31.0 ([7a45dde4f](https://gitlab.gnome.org/GNOME/glib/-/commit/7a45dde4f)).
Fixes #96.

config-file: remove trailing spaces from string/bool/group option values

---

CMakeLists.txt
src/rauc-hawkbit-updater.c

Do not treat version as float which would limit versions to major.minor. Instead handle it as string.
This way it is limited only by the restrictions CMake brings in (format must be major.minor.patch.tweak where each component must be a number).

allow more generic version numbering

---

src/hawkbit-client.c

`build_api_url()` can be called with `NULL` to get the base deployment URL. Passing `NULL` as a format argument to `g_strdup_vprintf()` returns `NULL` if `GLIB_USING_SYSTEM_PRINTF` is defined, otherwise it leads to a segmentation
fault. The format argument is explicitly documented as "not nullable", so we rely on undefined behavior here.
Skip over `va_start()`, `g_strdup_vprintf()`, `va_end()` for `path=NULL` to fix that.

hawkbit-client: do not pass NULL format to g_strdup_vprintf() in build_api_url()

---

docs/reference.rst

See src/config-file.c:
static const gint DEFAULT_RETRY_WAIT      = 5 * 60; // 5 min.
Fixes #74

docs: reference: correct retry_wait default value

---

test/conftest.py

To allow IPv6 addresses in `--hawkbit-instance`, split once at the rightmost colon instead of on every colon, which effectively
breaks IPv6 addresses.
By default, nginx only binds to IPv4. Allow usage of the testing proxy also via IPv6.

test: allow using remote hawkbit instance and nginx testing proxy via IPv6

---

src/hawkbit-client.c

This fails to compile against musl. The time.h include is sufficient.
Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@huawei.com>

Do not include glibc-specific bits/types/struct_tm.h

---

src/hawkbit-client.c

The `token` variables in `get_binary()`/`rest_request()` are obsolete since the refactoring of the curl options. So drop them.
`event_source` is only used within the `WITH_SYSTEMD` ifdef, so move its declaration there, too.

Drop unused variables

---

.github/workflows/tests.yml
README.md

Small collection of testing related improvements:
- github/README: drop python virtualenv test dependency
- README: clarify which calls must be run in the venv
- README: mention test dependencies

drop virtualenv test dependency, improve README

---

src/rauc-installer.c
src/rauc-installer.xml
test/conftest.py
test/rauc_dbus_dummy.py

Starting with RAUC [v1.3](https://github.com/rauc/rauc/releases/tag/v1.3), a new `InstallBundle()` D-Bus method for triggering installations was introduced.
Compared to the older `Install()` method, this one allows passing additional options to the installation process. This will be needed in a future PR introducing [streaming support](https://rauc.readthedocs.io/en/latest/advanced.html#http-streaming) in rauc-hawkbit-updater.
The older `Install()` method was deprecated and is likely to be removed in any later versions of RAUC.
To be able to use the new method, sync the D-Bus interface XML with upstream RAUC, adjust the dummy D-Bus interface for testing to expose the method and use the new method in rauc-hawkbit-updater's rauc-installer accordingly. While at it, implement the remaining …

Use RAUC's InstallBundle() D-Bus method instead of Install()

---

test/conftest.py
test/test_cancel.py
test/test_install.py

The tests run various processes, such as rauc-hawkbit-updater, nginx or rauc_dbus_dummy. The output of these processes is currently only read until we see the string/regex we expect. Everything else is not read and does not end up in the logs.
This is confusing to the person running the tests, because errors, tracebacks and other output the tests do not rely on is not logged.
To change this, read all relevant process output (until `EOF`) after the processes are terminated.
While at it, drop an unused line from conftest. It was there since the introduction of the Python test suite. It is a relict of a prior implementation.

test: read output of process until EOF

---

test/helper.py

The test suite runs various commands, e.g. rauc-hawkbit-updater, nginx, but also stand-alone python modules, e.g. rauc_dbus_dummy (see #83, d63f0e02 ("test: add RAUC D-Bus dummy helper") for the reasoning).
Until now the first component of the command is used as the name of the logger, so we know which command printed what stdout/stderr lines. Since the python module is called via `/path/to/venv/bin/python -m modulename`, the first component might not be helpful and long.
So use the basename of the first component generally. If this component happens to be the Python interpreter called with a module, use the module's name as the name of the logger.
This should help identify the actual command emitting output during tests.

test: helper: use basename or python module as logger name

---

src/config-file.c
test/test_basics.py

Drop unnecessary redundancies in error messages, since they are prefixed with "Loading config file failed: " anyway. Drop periods at the end of the messages. Use single quotes around option names for better comprehensibility.

config-file/test: make error messages more consistent

---

README.md

`enable_streaming` should be `stream_bundle`
Sorry for the multiple PRs. I got confused how to add the Signed-oof and then used the wrong branch.
Signed-off-by: Lukas Reinecke <lukas.reinecke@epis.de>
Fixes: #142

Fixed inconsistency in README.md

---

docs/reference.rst

As explained in #130, bundle streaming with hawkBit does not work work with hawkBit's default configuration (for most cases). Until now, the configuration options were only added to the test suite section of the README. No explanation was provided (not considering the PR and the commit messages).
To change that, add all required configuration options and an explanation to the reference docs of `stream_bundle`.
While at it, also mention the default value of the option.

docs: reference: improve stream_bundle documentation

---

.github/workflows/tests.yml

Fixes warnings such as [1]:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-python, docker/login-action, docker/login-action, actions/setup-python, actions/checkout
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: …
```

github: bump action versions to fix deprecation warnings

---

src/hawkbit-client.c
test/test_install.py

Since the integration of RAUC streaming support in rauc-hawkbit-updater [1] the `bundle_download_location` config option can be ommited when the `stream_bundle` config option is enabled [2].
The value of the `bundle_download_location` config option is still used in streaming installation code paths leading to errors such as:
```
g_file_test: assertion 'filename != NULL' failed
```
To fix this, exit early in bundle clean up code and omit the check for free space if the `stream_bundle` config option is enabled.
We should omit the `bundle_download_location` config option for streaming installations in the install tests, because this is the critical code path for streaming installations. Specifying the option for this use case does not make a difference, so we do not need to test it.
[1] …

Fix Omitted Bundle Download Location For Streaming Installations

---

test/helper.py

In case of timeout stdout in github actions is truncated, which makes it more difficult to understand the failure. This patch addresses this issue

test: helper: Print stdout on timeout

---

.github/workflows/codeql.yml
.readthedocs.yaml
README.md

* lgtm has gone -> replace by CodeQL
* also replace badges
* readthedocs browns out -> add config file
* minor fixes and extensions of README.md

Project Maintenance Fixes

---

.github/workflows/tests.yml
README.md
meson.build

- github: tests: use non-ambiguous "meson setup build"
- meson: decrease warning_level to 2
- github/README: add libcairo2-dev to test dependencies
This should also fix the CI builds/tests.

Build and Test Fixes

---

.github/workflows/codeql.yml

v2 is deprecated [1], so switch to v3.
[1] https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/

github: codeql: bump to v3

---

.github/workflows/tests.yml
README.md
test/conftest.py

For testing purposes, it is generally not needed to bind against anything else than localhost. A malicious actor can potentially do bad things with the default configuration of the hawkbit container, so bind locally only.
Depending on the system configuration, localhost can resolve to ::1 or 127.0.0.1. docker does not support binding to localhost, only to an IP address. So simply let nginx and the hawkbit docker container bind to both IPv4 and IPv6 locally.

testing: bind hawkbit/nginx locally only

---

src/hawkbit-client.c

Using a curl_share between curl requests allows sharing an open connection and re-use cached DNS, PSL and TLS session id.
This change allows performing multiple requests without having to do re-perform the (full) TLS handshake.
For reference, on a stm32mp151c with OPTEE + pkcs11 TA a full TLS handshake takes ~8 seconds. Mostly due to small pager pool (internal sram) available for OPTEE.
With this change a mTLS curl request take around 60ms after the initial connection has been established.

Share connection between curl requests

---

.github/workflows/tests.yml
README.md
test/conftest.py
test/nginx/base.conf.in
test/nginx/partial.inc.in

Until now, the partial download tests did not work reliably and relied on implicit nginx behavior: `limit_rate_after 200k;` combined with `limit_rate 70k;` lead to nginx sending "206 Partial Content" responses. As far as I remember, this was found by trial and error.
Let's use a more stable solution: lua scripting allows us to control reliable and fine grained what hawkBit artifacts nginx serves. So add a config snippet that makes nginx only serve the first half of the RAUC bundle, then close the connection prematurely and serve the second half via range request only. This is basically what the previous solution tried to achieve in a more reliable fashion.   
This means we need to add the lua module and its dependencies to the test dependencies.
The nginx config is getting rather complex …

test: rework nginx partial download fixture, move nginx config snippets to dedicated files

---

test/conftest.py
test/nginx/base.conf.in

Logs
$ ./test/wait-for-hawkbit-online && dbus-run-session -- pytest -v -o log_cli=true test/test_download.py
[...]
test/test_download.py::test_download_too_slow
-------------------------------------------------------- live log call --------------------------------------------------------
INFO nginx running: nginx -c /tmp/pytest-of-thibaud/pytest-8/nginx0/nginx.conf -p .
INFO nginx nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
INFO nginx 2024/06/28 15:41:56 [emerg] 1450257#1450257: mkdir() "/var/lib/nginx/tmp/client_body" failed (13: Permission denied)
SKIPPED (nginx failed, use -s to see logs)                                                                              [ 42%] …

test: fix nginx to run as non-root user
