src/hawkbit-client.c

Signed-off-by: Niklas Johansson <niklas.johansson@prevas.dk>

rest_request: clean up curl on malloc failure

---

include/json-helper.h
src/hawkbit-client.c
src/json-helper.c
src/log.c

Hi,
I've let lgtm -- that we use for RAUC, too -- told to scan your repository.
It reported 4 issues for that these are my proposed fixes.
If that's done I would vote for adding the badge to the badge collection in README:
￼
[![Language grade: C/C++](https://img.shields.io/lgtm/grade/cpp/g/prevas-dk/rauc-hawkbit-updater.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/prevas-dk/rauc-hawkbit-updater/context:cpp)
My expectation is that the color becomes much greener with the fixes merged ;)
Regards, Enrico

Add Fixes revealed by lgtm

---

src/config-file.c
src/hawkbit-client.c
src/log.c
src/rauc-installer.c

This is a collection of patches making functions only internally used static.
This prepares for allowing more picky compiler checks and gain more robust and optimized code.

make internal functions static

---

.travis.yml
.uncrustify.cfg
build-uncrustify.sh
src/config-file.c
src/hawkbit-client.c
src/log.c
src/rauc-hawkbit-updater.c
src/rauc-installer.c
uncrustify.sh

This gives the code a consistent coding style.

Add support for uncrustify code beautifier

---

README.md

Signed-off-by: Enrico Jorns <ejo@pengutronix.de>

README.md: finalize move to 'rauc' GitHub organization

---

src/hawkbit-client.c

Collect and forward the actual error in `get_available_space()`.
Otherwise an invalid download path for example will result in an error
like:
> CRITICAL: Error: Not enough free space. File size: 5661. Free space: -1
With this fix, the same situation will tell:
> CRITICAL: Error: Failed to calculate free space: No such file or directory

src/hawkbit-updater: add GError handling for get_available_space

---

README.md
config.conf.example
include/config-file.h
src/config-file.c
src/hawkbit-client.c
test/rauc-hawkbit-updater.t
test/test-config-auth-token-only.conf
test/test-config-both-security-tokens.conf
test/test-config-gateway-token-only.conf
test/test-config-no-security-tokens.conf

Authentication with gateway token: https://www.eclipse.org/hawkbit/concepts/authentication/

Gateway token support

---

README.md

README.md: proper syntax highlighting for config file

---

src/hawkbit-client.c

Avoid resource leak by closing fd.

src/hawkbit-client: Avoid resource leak

---

src/hawkbit-client.c

This fixes #45 (memory leak on debug messages). 
NOTE: Although I detected the leak, it was @hpatriarche  who truly was able to trace it to its source. Therefore, I'm just the committer.

hawkbit-client: Fix memory leak on debug messages

---

src/hawkbit-client.c

This simplifies usage of `build_api_url()` that is always used for
constructing API strings with g_strdup_printf()`.
As the memory allocated was not always freed but sometimes directly
passed this also fixes some memory leakages.
The `__attribute__` tells the compiler to validate the 'path' argument to
be in the right format for the provided arguments.

src/hawkbit-client: var args support for build_api_url()

---

include/hawkbit-client.h
src/config-file.c
src/hawkbit-client.c
src/json-helper.c
src/rauc-hawkbit-updater.c
src/rauc-installer.c

Small collection of fixes and improvements I came up with while integrating rauc-hawkbit-updater into a customer BSP.

hawkbit-client/rauc-hawkbit-updater: fixes and improvements

---

src/rauc-hawkbit-updater.c

This is the next PR of a series of PRs to refactor and clean up the code base, get rid of bugs (memory leaks, use-after-frees, race conditions), simplify functions and document them.
In this iteration I focused on the `rauc-hawkbit-updater` module.

rauc-hawkbit-updater: refactoring

---

README.md
config.conf.example
include/config-file.h
script/rauc-hawkbit-updater.service
src/config-file.c
src/hawkbit-client.c
test/test-config-auth-token-only.conf
test/test-config-both-security-tokens.conf
test/test-config-gateway-token-only.conf
test/test-config-no-security-tokens.conf
test/test-config.conf

To reboot system after an update set "post_update_reboot" variable in config
file accordingly.

Add a reboot option

---

include/hawkbit-client.h
src/hawkbit-client.c
test/rauc-hawkbit-updater.t

This is the next PR of a series of PRs to refactor and clean up the code base, get rid of bugs (memory leaks, use-after-frees, race conditions), simplify functions and document them.
In this iteration I focused on the `hawkbit-client` module.

hawkbit client: refactoring and bug fixes

---

README.md

This adds two badges to REAME.md.

Add matrix and documentation badges

---

CHANGES
CMakeLists.txt
docs/conf.py
src/config-file.c
src/hawkbit-client.c
src/rauc-hawkbit-updater.c
src/rauc-installer.c

Updated release notes and version tags in sources and scripts.
Added dist package generation in CMake.

Prepare for release 1.0

---

CHANGES

This shortly describes changes done since v1.0 release

CHANGES: prepare for v1.1 release

---

CHANGES

This shortly describes changes done since v1.1 release
Signed-off-by: Enrico Jorns <ejo@pengutronix.de>

CHANGES: prepare for v1.2 release

---

.github/workflows/tests.yml

This trigger allows us to run the test suite with a push on a button.

github: add workflow_dispatch trigger

---

docs/reference.rst
docs/using.rst
script/hawkbit_mgmt.py
src/hawkbit-client.c

Hawkbit's base URL was changed to eclipse.dev

Update Hawkbit's documentation references
